# Описание плагина
# поддерживаемые версии
# 1.16-1.21+
# актионы
# [close] - закрытие меню
# [openmenu] - открытие меню
# [command] - выполнение команд
# [sound] произведение звуков
message:
  error-no-item:
  - "[message] &#FFCC00▪ &#FFFFFFУ вас нет предмета &#FFA500%item_name%"
  successfully-buyer:
  - "[message] &#FFCC00▪ &#FFFFFFВы успешно продали &#FFA500%item_name% &#FFFFFFза &#FF0000%prince%"
  autobuyer-use:
  - "[message] &#FFCC00▪ &#FFFFFFВы продали скупщику &#FFA500%item_sell% &#FFFFFFштук, баланс &#FF0000%vault_eco_balance%"
  autobuyer-status:
  - "[message] &#FFCC00▪ &#FFFFFFАвто-скупщик &#FFA500%autobuyer_status%"
  error-permission:
  - "[message] &#FF0000▪ &#FFFFFFУ вас недостаточно прав"
  new-level:
  - "[message] &#FFFFFFВы достигли уровня &#FFCC00%new_level%"
  config-reload:
  - "[message] &#FFCC00▪ &#FFFFFFКонфиг успешно перезагружен"
placeholder:
  enable-autobuyer: "&c▪ &aВключен"
  disable-autobuyer: "&c▪ &cВыключен"
sound:
  sound_open_menu:
    sound: BLOCK_CHEST_OPEN
    pitch: 1.0 # Высота тона звука
    volume: 1.0 # Громкость звука
    enabled: true
  no-item-sound:
    sound: ENTITY_VILLAGER_NO
    pitch: 1.0
    volume: 1.0
    enabled: true
  autobuyer-sound:
    sound: BLOCK_NOTE_BLOCK_XYLOPHONE
    pitch: 1.0
    volume: 1.0
    enabled: true
database:
  file: playerdata.db # название файла sqlite
bossbar-settings:
  bossbar: true
  text: "&c▪ &fУ вас &aвключён &cавто-скупщик"
  color: RED
  autobuyer-time: 40
buyer-top:
  update-money: 14000 # максимальная сумма от которой будет обновление топов
  update-interval: 20 # время обновления топов
register-menu:
  - "menu/menu.yml"
  - "menu/mine.yml"
  - "menu/farma.yml"
  - "menu/mob.yml"