# Описание плагина
# поддерживаемые версии
# 1.16-1.21+
# Зависимости
# Vault, PlaceholderAPI
# актионы
# [close] - закрытие меню
# [openmenu] - открытие меню
# [command] - выполнение команд
# [sound] произведение звуков
# Плагин разработан студией EryDev
sound:
  sound_open_menu:
    sound: BLOCK_CHEST_OPEN
    pitch: 1.0 # Высота тона звука
    volume: 1.0 # Громкость звука
    enabled: true
  no-item-sound:
    sound: ENTITY_VILLAGER_NO
    pitch: 1.0
    volume: 1.0
    enabled: true
  exchange-sound:
    sound: BLOCK_NOTE_BLOCK_XYLOPHONE
    pitch: 1.0
    volume: 1.0
    enabled: true
  autobuyer-sound:
    sound: BLOCK_NOTE_BLOCK_XYLOPHONE
    pitch: 1.0
    volume: 1.0
    enabled: true
bossbar-settings:
  bossbar: true
  text: "&fУ вас &aвключён &cавто-скупщик"
  color: RED
  autobuyer-time: 40
buyer-settings:
  enable-best-menu: true # Включить ли предметы повышенного спроса?
  update-custom-items: 14400 # время обновления предметов повышенного спроса
buyer-top:
  update-interval: 30 # секунд между обновлением топа игроков по поинтам
register-menu:
  - "menu/menu.yml"
  - "menu/mine.yml"
  - "menu/farma.yml"
  - "menu/mob.yml"
  - "menu/bestmenu.yml"