# Описание плагина
# поддерживаемые версии
# 1.16-1.21+
# Зависимости
# Vault, PlaceholderAPI
# актионы
# [close] - закрытие меню
# [openmenu] - открытие меню
# [command] - выполнение команд
# [sound] произведение звуков
# Плагин разработан студией EryDev
message:
  no-item: "&c▪ &fУ вас нет предмета &a%item_name%"
  successfully-buyer: "&c▪ &fВы успешно продали &a%item_name% &fза &#4A90E2%prince%"
  auto-buyer: "&c▪ &fВы продали скупщику &#FFFFFF%item_sell% &f штук баланс &a%balance%"
  auto-buyer-on: "&c▪ &fАвто-скупщик %autobuyer_status%"
  auto-buyer-off: "&c▪ &fАвто-скупщик %autobuyer_status%"
  no-permission: "&c▪ &4У вас недостаточно прав"
  level-up: "&#4A90E2🎉 Вы достигли уровня &#FFFFFF%new_level%"
  level-info:
    - "&fВаша статистика уровней"
    - ""
    - "&fОбщая сумма продаж %buyer_total_earned%"
    - "&fТекущий уровень %buyer_current_level%"
    - "&fДо следующего уровня %buyer_required_amount%"
placeholder:
  enable-autobuyer: "&c▪ &aВключен"
  disable-autobuyer: "&c▪ &cВыключен"
sound: # звуки
  sound_open_menu: BLOCK_CHEST_OPEN
  no-item-sound: ENTITY_VILLAGER_NO
  autobuyer-sound: BLOCK_NOTE_BLOCK_XYLOPHONE

bossbar-settings:
  bossbar: true
  text: "&c▪ &fУ вас &aвключён &cавто-скупщик"
  color: RED
  autobuyer-time: 80

levels:
  1:
    multiplier: 0.0
    required-money: 0.0
  2:
    multiplier: 0.1
    required-money: 16000.0
  3:
    multiplier: 0.2
    required-money: 35000.0
  4:
    multiplier: 0.3
    required-money: 70000.0
  5:
    multiplier: 0.5
    required-money: 140000.0

register-menu:
  - "menu/menu.yml"
  - "menu/mine.yml"
  - "menu/farm.yml"
  - "menu/mobs.yml"