name: EryBuyer
version: '1.4.3'
main: com.erydevs.EryBuyer
api-version: '1.16'
depend: [Vault]
softdepend:
  - PlaceholderAPI
commands:
  buyer:
    aliases:
      - seller
  autobuyer:
  level:
permission:
  erybuyer.open:
    default: op
  erybuyer.autobuyer:
    default: op