name: EryBuyer
version: 'v1'
main: com.erydevs.EryBuyer
api-version: '1.16'
depend: [Vault]
softdepend:
  - PlaceholderAPI
commands:
  erybuyer:
  buyer:
    aliases:
      - seller
      - скупщик
  autobuyer:
permission:
  erybuyer.admin:
    default: op
  erybuyer.open:
    default: op
  erybuyer.autobuyer:
    default: op